### ISSUE TITLE
Link issue - the link to the website from the youtube video is not working

### ISSUE THREAD

**Issue by schuetze** [t3knomanzer/maxmix-website#2]
Hi,

I have no idea on where to put this, but maybe you can check if the link from the youtube video:

https://www.youtube.com/watch?v=SEnBzFcOdMI

works for everyone.

It does not send me to the homepage, but to the

"https://github.com/t3knomanzer/ma" URL.

Cheers

**Comment by SchemingWeasels** [comment]
Hey, thanks for the report! Sorry for the delay. We're not currently actively monitoring this channel. 

Is this still an issue for you? Like you said, I cant reproduce the issue on my side.

You can reach the team and the community over on discord at https://discord.gg/TmvvgCw, we're very active over there!

**Comment by quadbyte** [comment]
Checked all the links on the YT videos, and they are now all working. Closing this, thanks.
